name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui-android

      - name: Restore Dependencies
        run: dotnet restore ./project/project.csproj

      - name: Build APK
        run: dotnet publish ./project/project.csproj -f net8.0-android -c Release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            **/*.apk
    
